files:
  - source: /app/src/main/res/values/*
    ignore:
      - styles.xml
      - keys.xml
      - ic*
      - dimens.xml
      - colors.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
