name: customdiceroller
description: A roller of custom dice
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-417.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  flutter_secure_storage: ^8.0.0
  isar_flutter_libs: ^3.1.0
  isar: ^3.1.0
  intl: any
  flutter_dotenv: ^5.0.2
  google_sign_in: ^6.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.9
  googleapis: ^11.0.0
  universal_internet_checker: ^0.1.2
  stupid: ^0.0.8
  path_provider: ^2.0.14
  xdg_directories: ^1.0.0
  darkstorm_common: ^1.0.0-pre.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  isar_generator: ^3.1.0
  build_runner: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .stupid