name: customdiceroller
description: A roller of custom dice
publish_to: 'none'
version: 1.2.0+12

environment:
  sdk: '>=3.0.0-417.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  uuid: ^4.1.0
  flutter_secure_storage: ^9.0.0
  isar_flutter_libs: ^3.1.0+1
  isar: ^3.1.0+1
  intl: any
  flutter_dotenv: ^5.1.0
  stupid: ^0.2.6
  googleapis: ^11.4.0
  path_provider: ^2.1.1
  package_info_plus: ^4.2.0
  xdg_directories: ^1.0.3
  darkstorm_common: ^1.0.10
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  isar_generator: ^3.1.0+1
  build_runner: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .stupid